project_id = "mimlfjkisguktiqqkpkm"

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-sync]
verify_jwt = false

[functions.gmail-attachments]
verify_jwt = false

[functions.gmail-search]
verify_jwt = false

[functions.process-scheduled-emails]
verify_jwt = false

[functions.process-email-reminders]
verify_jwt = false